---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: required

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible dnspython

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

before_script:
  # Create irods user
  - sudo useradd --system irods

  # Create the directory for the configuration files
  - sudo mkdir --parents /etc/irods

  # Give the irods user ownership
  - sudo chown --recursive irods:irods /etc/irods

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
