---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: required
group: deprecated-2017Q1

# Install ansible
addons:
  apt:
    packages:
    - python-pip
    - python-virtualenv

install:
  # Install ansible
  - pip install ansible dnspython

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' > ansible.cfg

before_script:
  # Add pip2.6 to the path
  - sudo ln -s $(which pip2.6) /usr/bin/pip2.6

  # Install pika for check
  - sudo -H pip2.6 install pika

  # Create irods user
  - sudo useradd --system --home-dir /var/lib/irods irods

  # Create the directory for the configuration files
  - sudo mkdir --parents /etc/irods /var/lib/irods/.irods /var/lib/irods/iRODS/server/bin/cmd

  # Give the irods user ownership
  - sudo chown --recursive irods:irods /etc/irods /var/lib/irods

script:
  # install role dependencies
  - ansible-galaxy install --role-file=tests/requirements.yml

  # The test
  - ansible-playbook --inventory-file=tests/inventory tests/main.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
