---
- name: place database_config.json
  template:
    src: etc/irods/database_config.json.j2
    dest: /etc/irods/database_config.json
    owner: irods
  when: inventory_hostname == irods_icat_host

- name: place server_config.json
  template:
    src: etc/irods/server_config.json.j2
    dest: /etc/irods/server_config.json
    owner: irods

- name: place irods_environment.json
  template:
    src: var/lib/irods/irods/irods_environment.json.j2
    dest: /var/lib/irods/.irods/irods_environment.json
    owner: irods

- include: install_amqptopicsend.yml 
  when: inventory_hostname == irods_icat_host

- name: remove aegis-env.re
  file:
    path: /etc/irods/aegis-env.re
    state: absent

- name: place static config in /etc/irods
  copy:
    src: "{{ item }}"
    dest: /etc/irods/
    owner: irods
  with_fileglob:
    - "etc/irods/*"

- name: place ipc-env.re
  template:
    src: etc/irods/ipc-env.re.j2
    dest: /etc/irods/ipc-env.re
    owner: irods

- name: place sernec-env.re
  template:
    src: etc/irods/sernec-env.re.j2
    dest: /etc/irods/sernec-env.re
    owner: irods
