---
- name: place database_config.json
  template:
    src: etc/irods/database_config.json.j2
    dest: /etc/irods/database_config.json
    owner: irods
  when: inventory_hostname == irods_icat_host

- name: place server_config.json
  template:
    src: etc/irods/server_config.json.j2
    dest: /etc/irods/server_config.json
    owner: irods

- name: place irods_environment.json
  template:
    src: var/lib/irods/irods/irods_environment.json.j2
    dest: /var/lib/irods/.irods/irods_environment.json
    owner: irods

- include: install_amqptopicsend.yml 
  when: inventory_hostname == irods_icat_host

- name: place static config in /etc/irods
  copy:
    src: "{{ item }}"
    dest: /etc/irods/
    owner: irods
  with_fileglob:
    - "etc/irods/*"
  register: statics

- name: place ipc-env.re
  template:
    src: etc/irods/ipc-env.re.j2
    dest: /etc/irods/ipc-env.re
    owner: irods
  register: ipc_env

- name: place bisque-env.re
  template:
    src: etc/irods/bisque-env.re.j2
    dest: /etc/irods/bisque-env.re
    owner: irods
  register: bisque_env

- name: place sernec-env.re
  template:
    src: etc/irods/sernec-env.re.j2
    dest: /etc/irods/sernec-env.re
    owner: irods
  register: sernec_env

- name: ensure that config files are reloaded
  when: statics|changed or ipc_env|changed or bisque_env|changed or sernec_env|changed
  file:
    path: /etc/irods/core.re
    state: touch

