---
- name: place static config in /etc/irods
  copy:
    src: "{{ item }}"
    dest: /etc/irods/
    owner: irods
  with_fileglob:
    - "*"

- name: place templated config in /etc/irods
  template:
    src: "{{ item }}"
    dest: /etc/irods/{{ item | regex_replace('\.j2$', '') }} 
    owner: irods
  with_fileglob:
    - "*.j2"
