---
- name: place static config in /etc/irods
  copy:
    src: "{{ item }}"
    dest: /etc/irods/
    owner: irods
  with_fileglob:
    - "*"

- name: place ipc-env.re
  template:
    src: ipc-env.re.j2
    dest: /etc/irods/ipc-env.re
    owner: irods

- name: place server_config.json
  template:
    src: server_config.json.j2
    dest: /etc/irods/server_config.json
    owner: irods

- name: place database_config.json
  template:
    src: database_config.json.j2
    dest: /etc/irods/database_config.json
  when: irods_db is defined

- name: place irods_environment.json
  template:
    src: irods_environment.json.j2
    dest: /var/lib/irods/.irods/irods_environment.json
